<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom">
    <channel>
        <title>100UP Hosting Status</title>
        <link>https://status.100up.org</link>
        <description>100UP Hosting Status Page</description>
        <lastBuildDate>Tue, 30 Mar 2021 19:56:57 GMT</lastBuildDate>
        <docs>http://blogs.law.harvard.edu/tech/rss</docs>
        <generator>Statusfy</generator>
        <atom:link href="https://status.100up.org/feeds/incidents.en.xml" rel="self" type="application/rss+xml"/>
        <item>
            <title><![CDATA[Canada Host 4 network issues (again)]]></title>
            <link>https://status.100up.org/incidents/fc894108</link>
            <guid>https://status.100up.org/incidents/fc894108</guid>
            <pubDate>Sat, 13 Mar 2021 23:52:32 GMT</pubDate>
            <content:encoded><![CDATA[<div class="update-block">
          <div class="update-block-date">2021-03-13T23:52:32.558Z</div>
          <div class="update-block-content">
            <div class="update-block-title">Identified</div>
            <div class="update-block-body">
<p>Host 4 is pinging out again. IPMI is timing out. OVH is informed.</p>
</div></div></div>
<div class="update-block">
          <div class="update-block-date">2021-03-14T12:52:32.558Z</div>
          <div class="update-block-content">
            <div class="update-block-title">Solved</div>
            <div class="update-block-body">
<p>OVH finally resolved the issue. Host 4 is online again without lag or packet loss.</p>
</div></div></div>
<!--- language code: en -->
]]></content:encoded>
        </item>
        <item>
            <title><![CDATA[Canada Host 4 network issues]]></title>
            <link>https://status.100up.org/incidents/1a32b31e</link>
            <guid>https://status.100up.org/incidents/1a32b31e</guid>
            <pubDate>Thu, 11 Mar 2021 21:11:25 GMT</pubDate>
            <content:encoded><![CDATA[<div class="update-block">
          <div class="update-block-date">2021-03-12T12:11:25.268Z</div>
          <div class="update-block-content">
            <div class="update-block-title">Resolved</div>
            <div class="update-block-body">
<p>All services are online again. OVH confirmed that the server was inaccessible from the network due to a network issue.</p>
<p>Task was: <a href="http://travaux.ovh.net/?do=details&amp;id=49523" target="_blank" rel="noopener noreferrer" class="external">http://travaux.ovh.net/?do=details&amp;id=49523</a></p>
</div></div></div>
<div class="update-block">
          <div class="update-block-date">2021-03-11T21:11:25.268Z</div>
          <div class="update-block-content">
            <div class="update-block-title">Identified</div>
            <div class="update-block-body">
<p>Host 4 started to show significant packet loss. After a reboot, it does not come online again. Hard reboot times out. IPMI times out. An OVH technician is already working on the rack.</p>
</div></div></div>
]]></content:encoded>
        </item>
        <item>
            <title><![CDATA[Fire in Strasbourg, France Data Center]]></title>
            <link>https://status.100up.org/incidents/5495ef8d</link>
            <guid>https://status.100up.org/incidents/5495ef8d</guid>
            <pubDate>Wed, 10 Mar 2021 01:47:58 GMT</pubDate>
            <content:encoded><![CDATA[<div class="update-block">
          <div class="update-block-date">2021-03-12T20:11:25.268Z</div>
          <div class="update-block-content">
            <div class="update-block-title">Update</div>
            <div class="update-block-body">
<p>OVH will take several weeks or more to bring the services in Strasbourg online again.</p>
<p>We have ordered new servers in Roubaix to temporarily restore all affected customers servers there. Sadly there is also no ETA for deliveries in Roubaix, but it should be around 15th March.</p>
</div></div></div>
<div class="update-block">
          <div class="update-block-date">2021-03-10T01:47:58.454Z</div>
          <div class="update-block-content">
            <div class="update-block-title">Identified</div>
            <div class="update-block-body">
<p>OVH Announcement: We are currently facing a major incident in our DataCenter of Strasbourg. If your production is in Strasbourg, we recommend to activate your Disaster Recovery Plan.</p>
<p>Detailed information <a href="http://travaux.ovh.net/?do=details&amp;id=49484" target="_blank" rel="noopener noreferrer" class="external">http://travaux.ovh.net/?do=details&amp;id=49484</a></p>
</div></div></div>
<div class="update-block">
          <div class="update-block-date">2021-03-30T20:47:58.454Z</div>
          <div class="update-block-content">
            <div class="update-block-title">Solved</div>
            <div class="update-block-body">
<p>OVH finally brought Host 9 located in SBG3 online again. Host 1 (SBG2) is destroyed.</p>
<p>Backups of all affected customers from Host 1 were restored to Host 9 and all VPS are online again.</p>
<p>All affected VPS were renewed at least 1 month due to the incident.</p>
</div></div></div>
<!--- language code: en -->
]]></content:encoded>
        </item>
        <item>
            <title><![CDATA[Reboot Host 5]]></title>
            <link>https://status.100up.org/incidents/4f20d413</link>
            <guid>https://status.100up.org/incidents/4f20d413</guid>
            <pubDate>Sat, 21 Dec 2019 03:42:36 GMT</pubDate>
            <content:encoded><![CDATA[<p>Reboot Host 5 to fix bugged cgroups.</p>
<!--- language code: en -->
]]></content:encoded>
        </item>
    </channel>
</rss>